[package]
name = "nelder_mead_optimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nelder_mead_optimizer"
crate-type = ["cdylib"]

[dependencies]
nalgebra = "*"
pyo3 = "*"